export const GET_FILM = 'GET_FILM';

export const GET_FILM_SUCCESS = 'GET_FILM_SUCCESS';

export const SET_LOADING_FILM = 'SET_LOADING_FILM';

export const UPDATE_FILM_FIELDS_SUCCESS = 'UPDATE_FILM_FIELDS_SUCCESS';

export const UPDATE_FILM_FIELD = 'UPDATE_FILM_FIELD';
